volumes:
   mongo_db:
services:
   mongo_database:
      image: mongo
      environment:
         - MONGO_INITDB_ROOT_USERNAME=root
         - MONGO_INITDB_ROOT_PASSWORD=example
      volumes:
         - mongo_db:/data/db
      ports:
         - "27017:27017"
      networks:
         - micro_auto_pruebas

   mongo-express:
      image: mongo-express
      restart: always
      depends_on:
         - mongo_database
      ports:
         - "8081:8081"
      environment:
         - ME_CONFIG_MONGODB_ADMINUSERNAME=root
         - ME_CONFIG_MONGODB_ADMINPASSWORD=example
         - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo_database:27017/
      networks:
         - micro_auto_pruebas  

   app-crud:
    build:
      context: ./CRUD
    ports:
      - "8084:8084"
      - "8082:8082"
    environment:
      - user=root
      - password=example
      - host=mongo_database
      - port=27017
      - db=crud
    networks:
      - micro_auto_pruebas
networks:
  micro_auto_pruebas:
    external: true
      

